### ISSUE TITLE
在MacOS下第二次启动插件时鼠标点击全部失效

### ISSUE THREAD

**Issue by jae-jae** [fofolee/uTools-QuickerCommand#1]
![Untitled2](https://user-images.githubusercontent.com/5620429/57846603-2c02dc80-7807-11e9-883e-a7b6ceb1cb3a.gif)
查看上图演示，在MacOS下每次使用完插件后，再一次唤起插件时必须手动`退出`插件，插件的设置页面才能正常工作，否则点击插件设置页的任何按钮都没有反应。

**Comment by fofolee** [comment]
这个bug貌似在uTools升级了新版本后已经修复了
