### ISSUE TITLE
Can't execute powershell command

### ISSUE THREAD

**Issue by epoweripione** [fofolee/uTools-QuickerCommand#19]
Using powershell to execute below command doesn't work:
`Start-Process -FilePath "$env:comspec" -ArgumentList "/c wt" -WindowStyle Hidden -Verb RunAs`
![image](https://user-images.githubusercontent.com/16471398/81271912-4d478300-907f-11ea-92e3-2d7ba77d7fa4.png)

But when i using Windows PowerShell, this command work perfect.

By the way, i'm using `uTools-1.0.2-beta` running on windows 10-1909(18363.815).

**Comment by fofolee** [comment]
it works well on my computer
1.do you have a "uac"  popup window?
2.can you run other powershell command with this plugin?

**Comment by epoweripione** [comment]
I use `scoop` install `utools` before, today i try the installer, then it works.
