### ISSUE TITLE
添加terminal命令超过5秒未响应

### ISSUE THREAD

**Issue by Kennnnnnji** [fofolee/uTools-QuickerCommand#23]
![image](https://user-images.githubusercontent.com/34367558/85923015-2efd4700-b8ba-11ea-85c6-3f0330e3c579.png)
能够正常打开terminal，但是过5秒就报错闪退
![image](https://user-images.githubusercontent.com/34367558/85923005-17be5980-b8ba-11ea-903b-8588183193c4.png)

**Comment by fofolee** [comment]
> ![image](https://user-images.githubusercontent.com/34367558/85923015-2efd4700-b8ba-11ea-85c6-3f0330e3c579.png)
> 能够正常打开terminal，但是过5秒就报错闪退
> ![image](https://user-images.githubusercontent.com/34367558/85923005-17be5980-b8ba-11ea-903b-8588183193c4.png)

近期会有一个较大更新，会把system由同步改成异步，你这个问题会解决，不过新版本我会内置一个更加丰富的启动wt的命令
当前版本你把命令改成 start "" wt -d xxx 也能临时解决
