### ISSUE TITLE
能为“显示纯文本输出”加个loading提示吗？

### ISSUE THREAD

**Issue by moxuanyuan** [fofolee/uTools-QuickerCommand#24]
输出选择了“显示纯文本输出” 或“显示html格式的输出”，如果命令要执行好几秒，在按下回车或空格后，就好似一点反应也没有，这种感觉很不舒服，希望增加一个loading提示

**Comment by fofolee** [comment]
> 输出选择了“显示纯文本输出” 或“显示html格式的输出”，如果命令要执行好几秒，在按下回车或空格后，就好似一点反应也没有，这种感觉很不舒服，希望增加一个loading提示

近期将会有一个较大的更新，其中就包括实时显示命令的输出，类似ping这种命令不需要等了
