### ISSUE TITLE
建议加平台选项

### ISSUE THREAD

**Issue by mmqmzk** [fofolee/uTools-QuickerCommand#25]
有些跨平台的命令，比如 adb，不同的平台配置不一样 (cmd vs shell)，但是想用同样的关键字触发。

**Comment by mmqmzk** [comment]
自己试了一下写跨平台的脚本

···json
{
    "features": {
        "code": "key_1hrz1fagcvr",
        "explain": "adb",
        "cmds": [
            "adb"
        ],
        "icon": ""
    },
    "program": "javascript",
    "cmd": "const { spawn } = require('child_process')\nconst child = spawn('adb', '{{subinput}}'.trim().split(/\\s+/))\nchild.stdout.pipe(process.stdout)\nchild.stderr.pipe(process.stderr)\nchild.on('exit', code => process.exit(code))",
    "output": "text",
    "hasSubInput": true
}
```


```javascript
const { spawn } = require('child_process')
const child = spawn('adb', '{{subinput}}'.trim().split(/\s+/))
child.stdout.pipe(process.stdout)
child.stderr.pipe(process.stderr)
child.on('exit', code => process.exit(code))
```

Windows 下运行正常， ubuntu 下面按回车没反应，求教该如何调试？

**Comment by fofolee** [comment]
> 有些跨平台的命令，比如 adb，不同的平台配置不一样 (cmd vs shell)，但是想用同样的关键字触发。

近期将会有一个较大的更新，其中就包括平台选项，还有一个更新就是，win下选择shell的话可以通过wsl执行shell脚本，so在wsl下整个adb，也可以实现一个通用命令搞定
