### ISSUE TITLE
脚本的文件保存格式能否改为utf8

### ISSUE THREAD

**Issue by stilltooyoung** [fofolee/uTools-QuickerCommand#26]
![image](https://user-images.githubusercontent.com/22746567/86424044-0b039080-bd14-11ea-861c-909dd63b87cd.png)
脚本的文件保存格式能否改为utf8,或者支持手动设置

**Comment by fofolee** [comment]
> ![image](https://user-images.githubusercontent.com/22746567/86424044-0b039080-bd14-11ea-861c-909dd63b87cd.png)
> 脚本的文件保存格式能否改为utf8,或者支持手动设置

只有bat和ps1是gbk的，因为Win下不设置为gbk会有问题，你这边是出现乱码了吗

**Comment by stilltooyoung** [comment]
是的，我使用的PowerShell 7，输出编码设置的UTF-8，然后脚本中的中文就乱码了

**Comment by fofolee** [comment]
> 是的，我使用的PowerShell 7，输出编码设置的UTF-8，然后脚本中的中文就乱码了

环境选自定义，手动设置编码试下
