### ISSUE TITLE
如何处理 mac 系统执行 shell 命令后的弹窗

### ISSUE THREAD

**Issue by xuebkgithub** [fofolee/uTools-QuickerCommand#3]
详细配置截图如下
<img width="799" alt="image" src="https://user-images.githubusercontent.com/41730586/66452860-c43e7e00-ea94-11e9-9246-e4ad27209333.png">

报错如下.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/41730586/66452881-d9b3a800-ea94-11e9-92ef-70930c5aba5a.png">

内置的 shell 脚本里面 有 curl 命令. 请问这个如何处理

**Comment by fofolee** [comment]
试下curl -s

**Comment by fofolee** [comment]
或使用新版本的在终端输出
