### ISSUE TITLE
macOS下有多个python解释器时候，无法选择用户安装的python版本，只能用系统默认的python2 

### ISSUE THREAD

**Issue by oqyj** [fofolee/uTools-QuickerCommand#32]
macOS下有多个python解释器时候，无法选择用户安装的python版本，只能用系统默认的python2 

如图
系统命令行python显示3.9  在工具上为2.7

![](https://i.postimg.cc/BnLX9pJH/5fca617b51eeb.png)

**Comment by fofolee** [comment]
`环境` 下拉框拉到最下面，选择`custom`
