### ISSUE TITLE
Shell 脚本乱码问题

### ISSUE THREAD

**Issue by eallion** [fofolee/uTools-QuickerCommand#33]
创建了一个如图所示的脚本，向 CloudBase 数据库发送 POST 请求，但输出乱码。应该跟默认编码有关。这种编码错误一般是以 `ISO8859-1`编码读取 `UTF-8` 编码所致。

![Snipaste_2020-12-29_00-09-22](https://user-images.githubusercontent.com/1698841/103228435-ccb9f780-496b-11eb-95e0-c0cf4f7cbc18.png)

![Snipaste_2020-12-29_00-09-48](https://user-images.githubusercontent.com/1698841/103228502-f2df9780-496b-11eb-9382-c3625fbcbdf3.png)

**Comment by fofolee** [comment]
v2.2.0 会增加自定义设置编码的功能

**Comment by eallion** [comment]
谢谢！期待。

暂时用 Python 脚本代替了。

**Comment by eallion** [comment]
看到更新了，但还是不可用，尝试过所有编码组合。

请问子输入框是采用的什么编码的？

**Comment by fofolee** [comment]
> 看到更新了，但还是不可用，尝试过所有编码组合。
> 
> 请问子输入框是采用的什么编码的？

字输入框的内容会自动替换脚本文件里的{{subinput}}并最终用设定的编码保存到脚本文件里，你可以翻一翻 tmp 目录下的`QuickCommandTempScript.sh`看下保存的编码格式，并试下一下直接执行这个脚本会不会还有乱码

**Comment by eallion** [comment]
编码本身没有问题了。应该是 Shell 脚本的问题。
