### ISSUE TITLE
如何避免多次触发脚本

### ISSUE THREAD

**Issue by lie5860** [fofolee/uTools-QuickerCommand#5]
版本1.1.0
在mac和win下 使用js编写的快捷指令（python）好像也有？
第N次使用命令就触发N次结果
我命令是打开一个页面
第一次使用打开一个页面
第二次使用打开两个。。
第三次duang一下就弹出三个。。

**Comment by fofolee** [comment]
使用了子输入框吧，新版本已解决这个bug
